### ISSUE TITLE
Very useful tool !!!

### ISSUE THREAD

**Issue by sachinna** [vassim/linuxacademy-dl#11]
I am able to download courses on linux CentOS 7.2 but when i am trying to install it on Windows 10 its giving an error

PS C:\Users\DELL> pip install linuxacademy-dl
Collecting linuxacademy-dl
  Using cached linuxacademy-dl-1.0.dev2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DELL\AppData\Local\Temp\pip-build-3dfh3f30\linuxacademy-dl\setup.py", line 19
        print 'error'
                    ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\DELL\AppData\Local\Temp\pip-build-3dfh3f30\linux
academy-dl\

**Comment by thangduong3010** [comment]
what's your python version?

**Comment by sachinna** [comment]
Python 3.6.0

**Comment by thangduong3010** [comment]
print 'error' => python 2 syntax
run it with python 2 instead

**Comment by sachinna** [comment]
Yeah, Its working with Python 2.7.12
Thank you :)

**Comment by thangduong3010** [comment]
pleased to help :)
