### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by alfredogarza** [vassim/linuxacademy-dl#12]
I'm getting this error on Windows 7

PS C:\Users\XtC> python -m pip install linuxacademy-dl
Collecting linuxacademy-dl
  Using cached linuxacademy-dl-1.0.dev2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XtC\AppData\Local\Temp\pip-build-766cfw44\linuxacademy-dl\setup.py", line 19
        print 'error'
                    ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\XtC\AppData\Local\Temp\pip-build-766cfw
cademy-dl\

**Comment by vassim** [comment]
Hi @alfredogarza, Thanks for reporting this issue. I've already fixed this issue and it won't be there in the next version (v1.0a1)

**Comment by shardulsrivastava** [comment]
Hi @alfredogarza,you can avoid this error be using Python 2.7 version.
