### ISSUE TITLE
Cannot Render File

### ISSUE THREAD

**Issue by alfredogarza** [vassim/linuxacademy-dl#13]
Hi,

I downloaded some videos using Ubuntu 16.04, but I cannot open them, Media Player Classic state "Cannot render video file", are they now protected?

**Comment by vassim** [comment]
Hi @alfredogarza, Thank you for reporting this issue. It looks like a duplicate of #4.
You are correct, the video stream is now protected. But you needn't worry about that any more - I've already fixed the problem and this issue won't be there by v1.0a1.
