### ISSUE TITLE
Installation Failed With error Microsoft Visual 9.0++ is required

### ISSUE THREAD

**Issue by shardulsrivastava** [vassim/linuxacademy-dl#15]
Here is the Error Log

 copying lib\Crypto\Signature\__init__.py -> build\lib.win32-2.7\Crypto\Signature
 running build_ext
 warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
 building 'Crypto.Random.OSRNG.winrandom' extension
 error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

**Comment by vassim** [comment]
Hi @shardulsrivastava, Please visit http://www.voidspace.org.uk/python/pycrypto-2.6.1/, download a suitable PyCrypto distribution from there and install it in your system. Then try to install `linuxacademy-dl` again.
