### ISSUE TITLE
Never completed Login!

### ISSUE THREAD

**Issue by TBUtsav** [vassim/linuxacademy-dl#21]
always throw an error 
INFO     Logging in ...
ERROR    Username or email not found! Please try again.

**Comment by vassim** [comment]
Hi @TBUtsav, I don't think there is a bug in the login module. I think you are entering the wrong credentials or you must be entering it in a wrong way.

If you are running the application by supplying the user credentials through `-u` or `-p` flags, please make sure that you are escaping all the special characters with a `\`.

For example, if you want to use the following credentials with the utility,
[`UserN@me`, `pa$sw\0#d`]
you need to supply the user name and password like this
`linuxacademy-dl -u UserN\@me -p pa\$sw\\0\#d`
