### ISSUE TITLE
MissingSchema: Invalid URL 'None': No schema supplied.

### ISSUE THREAD

**Issue by mstickler** [vassim/linuxacademy-dl#22]
For this course "https://linuxacademy.com/cp/modules/view/id/44" download fails with the following error:

INFO     Debug log file created at /Users/mstickler/linuxacademy-dl/log/log_2017-03-16T07:36:38.573802.log
DEBUG    Python: CPython 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
DEBUG    Platform: Darwin-16.4.0-x86_64-i386-64bit [Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64]
DEBUG    OS: OS X - 10.12.3 x86_64
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Skipping already existing file /Volumes/MBP External/Learn/Courses/Linux Academy/_Media/AWS Certified Solutions Architect - Associate Level/9 - AWS Direct Connect/1 - Understanding AWS Direct Connect.mp4
INFO     Skipping already existing file /Volumes/MBP External/Learn/Courses/Linux Academy/_Media/AWS Certified Solutions Architect - Associate Level/20 - ImplementationDeployment/1 - How To Design Cloud Services & Best Practices.mp4
INFO     Skipping already existing file /Volumes/MBP External/Learn/Courses/Linux Academy/_Media/AWS Certified Solutions Architect - Associate Level/20 - ImplementationDeployment/2 - Monitoring.mp4
INFO     Skipping already existing file /Volumes/MBP External/Learn/Courses/Linux Academy/_Media/AWS Certified Solutions Architect - Associate Level/20 - ImplementationDeployment/3 - Architectural Trade-Off Decisions.mp4
INFO     Skipping already existing file /Volumes/MBP External/Learn/Courses/Linux Academy/_Media/AWS Certified Solutions Architect - Associate Level/20 - ImplementationDeployment/4 - Elasticity And Scalability.mp4
INFO     Skipping already existing file /Volumes/MBP External/Learn/Courses/Linux Academy/_Media/AWS Certified Solutions Architect - Associate Level/6 - Amazon RDS (Relational Database Service)/1 - RDS Essentials.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 130, in download
    self.analyze()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 126, in analyze
    self._resources = self.get_resources()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 123, in get_resources
    return processor()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 98, in __call__
    return self.process()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 92, in process
    'key': session.get(parser.parsed_data['uri']).content,
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Python/2.7/site-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/Library/Python/2.7/site-packages/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by vassim** [comment]
Hi @mstickler, Thanks for reporting this issue. I tried to reproduce this problem, but failed. I think this is happening because of some issues in the server side! If you are still facing this problem, please re open this issue! Thank you!

**Comment by mstickler** [comment]
Thanks, will see if I can find the reason why it fails for me.

**Comment by mstickler** [comment]
Hi @vassim, today I tried a dozen of times to see if I have more luck this time, but the error didn't chnage. I looked at your code and added a couple of debug statements to get a better understanding of the problem. In "parsers.py" the key "uri" has a default value of None. In the course I stated in the issue, the value remains at None for exactly one of the videos and this is where it fails. Changing the default to "https://linuxacademy.com/k/verify" - which every other video in the course has - fixes my problem.

class ChunkListParser(HLSParser):
    def __init__(self):
        self.parsed_data = {
            "encryption": None,
            "uri": "https://linuxacademy.com/k/verify",
            "iv": None,
            "chunks": []
        }

**Comment by vassim** [comment]
Thanks for your efforts @mstickler. I think I got the problem now!

**Comment by Muhamed-Hamid** [comment]
Hi @vassim , 

Is this updated in the original files or not ? as i still have the same bug mentioned by @mstickler

**Comment by mstickler** [comment]
Hi @Muhamed-Hamid,

there is no updated version yet, but for the time being you can fix it by applying the changes I stated above. Might not be the perfect solution, but it's a solution :D

**Comment by Muhamed-Hamid** [comment]
Hi @mstickler,

Thank you for that , it seems good to me , Appreciated your feedback. 

BR,
