### ISSUE TITLE
[FeatureRequest] Multiple course download

### ISSUE THREAD

**Issue by TBUtsav** [vassim/linuxacademy-dl#27]
please add multiple course download option or complete course like if I want to download complete aws course then currently I have to download individual course

**Comment by vassim** [comment]
Hi @TBUtsav, That was a great thought, and thank you for bringing that up! I'm sorry to say that I don't have any plans to add a 'multiple course downloading' feature in this app.
But you can easily achieve this by following a small trick as explained in [this link](http://stackoverflow.com/questions/4227994/command-line-arguments-from-a-file-content).

For example, in our case you can use:-
`linuxacademy-dl -u <username> -p <password> --use-ffmpeg -o <output_location> "$(< course_urls.txt)"`
