### ISSUE TITLE
SSL: InsecurePlatformWarning error

### ISSUE THREAD

**Issue by arush-sal** [vassim/linuxacademy-dl#6]
`INFO     Logging in ...`
`/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`
`  SNIMissingWarning`
`/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`
`  InsecurePlatformWarning`
`INFO     Analyzing ...`
`INFO     Downloading files ...`
`/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings`
`  InsecurePlatformWarning`
`INFO     Logged Out!`
`ERROR    Unknown Exception`
`ERROR    [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

I am facing above error while trying to run the code. Any troubleshooting points?

**Comment by vassim** [comment]
Hi @arush-sal, thanks for reporting this issue! This is happening because you are using older crypto libraries in your system. Please visit [this link](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package?answertab=active#tab-top) and follow the instructions carefully, it will fix your problem!
