### ISSUE TITLE
Username / Account not found September 2017 onwards facing issue

### ISSUE THREAD

**Issue by Aniketh-Raj** [vassim/linuxacademy-dl#61]
Hello Vassim,

I had initially created a free3 month subscription account of Linux Academy and was able to download one course of AWS.

But later on your code started giving me the error Username / Email 
![img_27112017_182526_0](https://user-images.githubusercontent.com/22044620/33267670-647ca526-d3a0-11e7-8dab-c29ebc602726.png)
not found.

But i am able to access the Linux Academy website using the same credentials I am giving in your script. I am able to open and view all course in the browser. But when i try to download any course using those credentials, its giving me error. Attached pic may give you a better picture.

Could you please look into this issue ??

BTW fantastic script you have created. Thanks a lot for this and Cheerio.

Regards,
Aniketh

**Comment by fclerg** [comment]
Hi @Aniketh-Raj,

This issue has already been reported via #58 and #59.
As mentionnes in #58, I fixed it in a fork with the branch [authentication-fixes](https://github.com/fclerg/linuxacademy-dl/tree/authentication-fixes) for which the pull request is still pending.

Meanwhile, you can clone and install the code from this branch as follow :

> git clone -b authentication-fixes https://github.com/fclerg/linuxacademy-dl.git
> python setup.py install

**Comment by Aniketh-Raj** [comment]
Hello @fclerg,

Yes i created this issue and then noticed the other two issues already created for the same.. plus you fixing the issue.. infact i already cloned it and started using it.. it works like a charm... No more errors... Thanks a lot again for fixing it on behalf of vassim...!!

**Comment by reddysrock** [comment]
same issue after following  steps
git clone -b authentication-fixes https://github.com/fclerg/linuxacademy-dl.git
python setup.py install
