### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by okian** [vassim/linuxacademy-dl#9]
unfortunately I'm not a python developer. I tried python 3.6, 3.5.3 and 3.5.0, any help to solve this problem will be appreciated.
```cmd
C:\Users\c>pip install --upgrade linuxacademy-dl
Collecting linuxacademy-dl
  Using cached linuxacademy-dl-1.0.dev2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\c\AppData\Local\Temp\pip-build-40jquj4o\linuxacademy-dl\setup.py", line 19
        print 'error'
                    ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\c\AppData\Local\Temp\pip-build-40jquj4o\linuxacademy-dl\
```

**Comment by arush-sal** [comment]
@okian  Exactly! The script is not python 3.5 ready, you will either have to use python 2.7 or you can use its [docker container](https://hub.docker.com/r/arush/linuxacademy-dl/).

**Comment by okian** [comment]
Then why in README it's says "prerequisites python (2 or 3)" ?!!
https://github.com/vassim/linuxacademy-dl#prerequisites

**Comment by arush-sal** [comment]
@okian My friend, that should be the question for the author @vassim 😅

**Comment by vassim** [comment]
Hi @okian, I've already fixed this issue, please try to install the latest version (v1.0a2) in your system.
